add_rules("mode.debug", "mode.release")
add_requires("tbb 2022.0.0")
target("AutoSign")
  set_languages("c++23")
  add_packages("tbb")
  add_defines("__AVX2__")
  add_cxxflags("clang::-mavx2")
  set_kind("binary")
  add_files("main.cpp")