name: C/C++ CI

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: chmod
      run: chmod 777 run.sh
    - name: run
      run: sudo ./run.sh