name: C/C++ CI

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.9.6'
        actions-cache-folder: '.xmake-cache'
    - name: install packages
      run: sudo apt update && sudo apt upgrade -y && sudo apt install -y wget 7zip clang-17
    - name: chmod
      run: chmod 777 down.sh
    - name: download
      run: sudo ./down.sh
    - name: unzip
      run: 7z x android.apk -oandroid_app
    - name: copy so
      run: cp android_app/lib/arm64-v8a/libminecraftpe.so libminecraftpe.so
    - name: config
      run: xmake f -p linux -a x86_64 -m release --toolchain=clang-17 -y
    - name: build
      run: xmake
    - name: copy build
      run: cp build/linux/x86_64/release/AutoSign ./
    - name: chmod
      run: chmod 777 AutoSign
    - name: run
      run: ./AutoSign