name: C/C++ CI

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.9.6'
        actions-cache-folder: '.xmake-cache'
    - name: chmod
      run: chmod 777 run.sh
    - name: run
      run: sudo ./run.sh